Repository ms-club-sliit/sliit-poson-web, pull requests merged in 2023-05, with the labels that each got.

#14 Create README.md
  README.md
Labels: documentation

#12 Create LICENSE
  LICENSE
Labels: documentation

#20 Dark Mode feature added
  index.html
  src/App.jsx
  src/components/DarkModeToggle/index.jsx
  src/components/index.js
  src/views/Committee/index.jsx
  src/views/Feedback/index.jsx
  src/views/Hero/index.jsx
  src/views/Mentors/index.jsx
  src/views/OurWork/index.jsx
  src/views/Team/index.jsx
  src/views/VesakZone/index.jsx
  tailwind.config.js
Labels: UI, feature

#23 Feature/mentors
  src/components/CarouselCard/CarouselCard.jsx
  src/data/mentors.js
  src/index.css
  src/views/Mentors/index.jsx
Labels: UI

#25 feat: create organising commitee carousel for both dark/light theme
  src/data/committee.js
  src/views/Committee/index.jsx
Labels: UI

#27 Hero sec
  package.json
  src/assets/images/Hero/img1.webp
  src/assets/images/Hero/img2.webp
  src/assets/images/Hero/img3.webp
  src/components/Header/index.jsx
  src/data/heroImages.js
  src/index.css
  src/views/Committee/index.jsx
  src/views/Hero/index.jsx
  src/views/Mentors/index.jsx
  src/views/VesakZone/index.jsx
  tailwind.config.js
  yarn.lock
Labels: UI

#30 feat: create our team page
  package-lock.json
  src/views/Committee/index.jsx
  src/views/Team/index.jsx
  yarn.lock
Labels: UI

#32 Completed Feedback Section
  src/views/Feedback/index.jsx
Labels: UI

#41 Bug Fix
  package.json
  src/components/Header/index.jsx
  src/data/heroImages.js
  src/routes/app-routes.jsx
  src/views/Home/index.jsx
  src/views/OurWork/index.jsx
  src/views/VesakZone/GuidelinesModal.jsx
  src/views/VesakZone/index.jsx
  yarn.lock
Labels: UI
